---
kind: pipeline
type: docker
name: default

metadata:
  namespace: default

steps:
  - name: Override
    image: node:12
    environment:
      DRONE_AUTH_TOKEN:
        from_secret: drone_auth_token
    commands:
      - bash prebuild.sh
  - name: Restore Cache
    image: meltwater/drone-cache:dev
    pull: true
    settings:
      backend: 'filesystem'
      restore: true
      cache_key: '{{ checksum "package.json" }}'
      archive_format: 'gzip'
      mount:
        - './node_modules'
        - './.wordpress-cache'
        - './public'
        - './.cache'

    volumes:
      - name: cache
        path: /tmp/cache

  - name: Build
    image: node:12
    environment:
      GATSBY_MAILGUN_DOMAIN:
        from_secret: GATSBY_MAILGUN_DOMAIN
      GATSBY_MAILGUN_API_KEY:
        from_secret: GATSBY_MAILGUN_API_KEY
      CRISP_WEBSITE_ID:
        from_secret: CRISP_WEBSITE_ID
      GOOGLE_ANALYTICS_TRACKING_ID:
        from_secret: GOOGLE_ANALYTICS_TRACKING_ID
      MAILCHIMP_ENDPOINT:
        from_secret: MAILCHIMP_ENDPOINT
      GRAPHQL_ENDPOINT:
        from_secret: GRAPHQL_ENDPOINT
    commands:
      - yarn install
      - yarn build

  - name: FTP Deploy
    image: cschlosser/drone-ftps:only-newer
    environment:
      FTP_USERNAME:
        from_secret: FTP_USER
      FTP_PASSWORD:
        from_secret: FTP_PASSWORD
      PLUGIN_HOSTNAME:
        from_secret: FTP_HOST
      PLUGIN_SECURE: false
      PLUGIN_VERIFY: false
      PLUGIN_SRC_DIR: /public
      PLUGIN_DEST_DIR: /public_html
    only_newer: true

  - name: Rebuild Cache
    image: meltwater/drone-cache:dev
    pull: true
    settings:
      backend: 'filesystem'
      rebuild: true
      cache_key: '{{ checksum "package.json" }}'
      archive_format: 'gzip'
      mount:
        - './node_modules'
        - './.wordpress-cache'
        - './public'
        - './.cache'
    volumes:
      - name: cache
        path: /tmp/cache

  - name: Notification
    image: plugins/slack
    when:
      status:
        - failure
    settings:
      webhook:
        from_secret: SLACK_TAMETO
      channel: tameto-builds
      link_names: true
      template: >
        {{#success build.status}}
          {{repo.name}}: :white_check_mark: Build #{{build.number}} succeeded!
          {{build.link}}
        {{else}}
          {{repo.name}} :x: Build #{{build.number}} failed. Fix me please.
          {{build.link}}
        {{/success}}

volumes:
  - name: cache
    host:
      path: /var/lib/cache
